unique_ids:
  assets:
    standard-page.html: EY7DAK335COSEAMX445IO2HFND3ZCPKW
    theme.css: OXN3UMQGDI2WTFED7TABOQYSC47KRSMW
  forms:
    MainPage: '1772013114244807481093978.7709'
  modules: {}
  scripts: {}
  server_modules: {}
